### ISSUE TITLE
Cake3 support

### ISSUE THREAD

**Issue by heat** [vexus2/CakeStorm#22]
You guys would start to think cake3 support.

**Comment by wouter0100** [comment]
This would be awesome!

**Comment by basteyy** [comment]
+1

**Comment by Laykou** [comment]
It would be great to support also migrations and genartors and tests with PHP Unit and [CakePHP Codeception](https://github.com/cakephp/codeception) as it is in RubyMine for RubyOnRails.

The CakePHP 3.0 should be released as stable in several weeks and this Cake3 plugin would be amazing to have.

**Comment by vexus2** [comment]
I'll support CakePHP3 in less than two months. Don't Miss It!!

**Comment by basteyy** [comment]
Sounds great!

**Comment by Spriz** [comment]
Sounds great @vexus2 ! How is it going?

**Comment by vexus2** [comment]
I just released that. :smile: 
Please report it an issue if have a problem.

https://plugins.jetbrains.com/plugin/7277

**Comment by nycomar** [comment]
I just tested with a CakePHP 3 project, and it works well :+1:

**Comment by Spriz** [comment]
To me it doesn't work at all on OS X - where did you test @Omar?

Mvh,
Mikkel Bonde
Reberbansgade 52 2. mf
9000 Aalborg

Kontakt:
#: 28 68 01 33
@: mikbonde@gmail.com

**Comment by vexus2** [comment]
@Spriz thanks. Create a new Issue please!

**Comment by nycomar** [comment]
I tested with PHPStorm 9.0.2 on Windows 8.1 @Spriz
