### ISSUE TITLE
Hi suport for CakePHP 3..?

### ISSUE THREAD

**Issue by EOM** [vexus2/CakeStorm#25]
Hi suport for cakePHP 3 new version..?
plugin for future update..?

**Comment by vexus2** [comment]
I'll support CakePHP3 in less than two months. Don't Miss It!!

**Comment by jtraulle** [comment]
Great news :star2: !

Many thanks :+1:

**Comment by EOM** [comment]
**Yes !!!**
Great news :star2: !
Many thanks :+1::+1::+1::+1:

**Comment by TheFRedFox** [comment]
I'm looking forward to this! :smiley:
Many thanks!! :star2::+1:

**Comment by Spriz** [comment]
Sounds nice @vexus2!  :+1: :+1:

**Comment by jtraulle** [comment]
@vexus2 have you had a chance to work on this ? :ok_hand:

**Comment by jtraulle** [comment]
@vexus2 have you had a chance to work on this ? :ok_hand:

**Comment by netstyler** [comment]
:+1: :+1:

**Comment by vexus2** [comment]
There is no progress too much :cry: wait a moment
https://github.com/vexus2/CakeStorm/tree/feature/cakephp3

**Comment by vexus2** [comment]
I just released that. :smile: 
Please report it an issue if have a problem.

https://plugins.jetbrains.com/plugin/7277
