### ISSUE TITLE
CakeStorm Crashed with PHPStorm 9.0.2

### ISSUE THREAD

**Issue by martinvahi** [vexus2/CakeStorm#30]
1) Started PHPStorm
2) Clicked on the bubble that advertised CakeStorm update
3) Restarted PHPStorm by clicking on the "Restart" link at "output" panel.
4) Observed the exception

    3:01:21 AM PluginException: com/vexus2/cakestorm/reference/CakeStormReferenceContributor : Unsupported major.minor version 52.0 [Plugin: com.vexus2.cakestorm]

5) Wrothe this bug report by copy/pasting the following text from PHPStorm bug reporting form:

    com/vexus2/cakestorm/reference/CakeStormReferenceContributor : Unsupported major.minor version 52.0 [Plugin: com.vexus2.cakestorm]

**Comment by ecramer** [comment]
+1 having the same issue. Same version of PHPStorm.

**Comment by Hanmac** [comment]
happens with IntelliJ IDEA 14.1.4 too

**Comment by AshWhitear** [comment]
+1 from me also..

**Comment by NaranjaWeb** [comment]
For my PHPStorm 8.0.3, too.
This seems to be the problem of java, not the plugin itself.
Could you please think of compiling the source by java 1.8, not by 1.7.

**Comment by pdphilip** [comment]
Same here I'm afraid (v9) - can't seem to roll back to 0.5.3 either... Have realised how much I depend on cakestorm now that it's gone - bring her back to life please!

**Comment by vexus2** [comment]
I just published v0.6.1. please try that
https://plugins.jetbrains.com/plugin/7277

**Comment by Hanmac** [comment]
v0.6.1 seems to work with IntelliJ IDEA 14.1.5 as far as i did see (no error yet)

**Comment by martinvahi** [comment]
It seems that the new version does not crash immediately, so, as a starter of this thread, I'll close this issue for now, but I close it with a reservation that people, who use the plugin more extensively than I do, should test the plugin and re-open this issue, if a crash occurs.
Thank You for reading my comment. :-)
